### ISSUE TITLE
Win 8.1 Error

### ISSUE THREAD

**Issue by OnorioCatenacci** [bbense/erlman#2]
Hi Booker,

Not sure how you wanted people to get back to you after they tried this.  I just tried on Win 8.1 with Erlang 17.5.  This is what I get:

Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Erlh.h ":os"
*\* (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
    (elixir) lib/io.ex:329: IO.chardata_to_string(nil)
    (elixir) lib/path.ex:467: Path.join/2
    (erlman) lib/erlman.ex:39: Erlman.manpage/1
    (erlman) lib/erlman.ex:53: Erlman.manstring/1
    (erlman) lib/erlman.ex:164: Erlman.get_docs/2
    (erlman) lib/erlh.ex:15: Erlh.h/1
iex(1)> Erlh.h
*\* (UndefinedFunctionError) undefined function: Erlh.h/0
    (erlman) Erlh.h()

I just copied your sample code for sake of simplicity.

**Comment by bbense** [comment]
Thanks that is very useful.
- Booker

**Comment by OnorioCatenacci** [comment]
You're welcome.

On Tue, Jun 16, 2015 at 12:26 PM, bbense notifications@github.com wrote:

> Thanks that is very useful.
> - Booker
> 
> On Tuesday, June 16, 2015, Onorio Catenacci notifications@github.com
> wrote:
> 
> > Hi Booker,
> > 
> > Not sure how you wanted people to get back to you after they tried this.
> > I
> > just tried on Win 8.1 with Erlang 17.5. This is what I get:
> > 
> > Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for
> > help)
> > iex(1)> Erlh.h ":os"
> > *\* (FunctionClauseError) no function clause matching in
> > IO.chardata_to_string/1
> > (elixir) lib/io.ex:329: IO.chardata_to_string(nil)
> > (elixir) lib/path.ex:467: Path.join/2
> > (erlman) lib/erlman.ex:39: Erlman.manpage/1
> > (erlman) lib/erlman.ex:53: Erlman.manstring/1
> > (erlman) lib/erlman.ex:164: Erlman.get_docs/2
> > (erlman) lib/erlh.ex:15: Erlh.h/1
> > iex(1)> Erlh.h
> > *\* (UndefinedFunctionError) undefined function: Erlh.h/0
> > (erlman) Erlh.h()
> > 
> > I just copied your sample code for sake of simplicity.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bbense/erlman/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bbense/erlman/issues/2#issuecomment-112488083.

## 

Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by bbense** [comment]
Can you send me the output of this command on your system?

iex> :os.find_executable('erl')

thanks,
- Booker C. Bense

**Comment by OnorioCatenacci** [comment]
Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :os.find_executable('erl')
'c:/Program Files/erl6.4/erts-6.4/bin/erl.exe'
iex(2)>

**Comment by OnorioCatenacci** [comment]
Posted.

On Tue, Jun 16, 2015 at 2:38 PM, bbense notifications@github.com wrote:

> Can you send me the output of this command on your system?
> 
> iex> :os.find_executable('erl')
> 
> thanks,
> - Booker C. Bense
> 
> On Tue, Jun 16, 2015 at 9:29 AM, Onorio Catenacci <
> notifications@github.com>
> wrote:
> 
> > You're welcome.
> > 
> > On Tue, Jun 16, 2015 at 12:26 PM, bbense notifications@github.com
> > wrote:
> > 
> > > Thanks that is very useful.
> > > - Booker
> > > 
> > > On Tuesday, June 16, 2015, Onorio Catenacci notifications@github.com
> > > wrote:
> > > 
> > > > Hi Booker,
> > > > 
> > > > Not sure how you wanted people to get back to you after they tried
> > > > this.
> > > > I
> > > > just tried on Win 8.1 with Erlang 17.5. This is what I get:
> > > > 
> > > > Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for
> > > > help)
> > > > iex(1)> Erlh.h ":os"
> > > > *\* (FunctionClauseError) no function clause matching in
> > > > IO.chardata_to_string/1
> > > > (elixir) lib/io.ex:329: IO.chardata_to_string(nil)
> > > > (elixir) lib/path.ex:467: Path.join/2
> > > > (erlman) lib/erlman.ex:39: Erlman.manpage/1
> > > > (erlman) lib/erlman.ex:53: Erlman.manstring/1
> > > > (erlman) lib/erlman.ex:164: Erlman.get_docs/2
> > > > (erlman) lib/erlh.ex:15: Erlh.h/1
> > > > iex(1)> Erlh.h
> > > > *\* (UndefinedFunctionError) undefined function: Erlh.h/0
> > > > (erlman) Erlh.h()
> > > > 
> > > > I just copied your sample code for sake of simplicity.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/bbense/erlman/issues/2.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/bbense/erlman/issues/2#issuecomment-112488083.
> > 
> > ## 
> > 
> > Onorio Catenacci
> > 
> > http://onor.io
> > http://www.google.com/+OnorioCatenacci
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bbense/erlman/issues/2#issuecomment-112488909.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bbense/erlman/issues/2#issuecomment-112524083.

## 

Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by bbense** [comment]
I think my latest changes should "fix" this error. If I am correct, then you should just get 

```
 iex> Erlh.h ":os"
 []
```

since the error occurs because erlman can't find any man pages.

**Comment by OnorioCatenacci** [comment]
I'll pull your changes and test as soon as I can.

On Thu, Jun 18, 2015 at 10:37 AM, bbense notifications@github.com wrote:

> I think my latest changes should "fix" this error. If I am correct, then
> you should just get
> 
>  iex> Erlh.h ":os"
>  []
> 
> since the error occurs because erlman can't find any man pages.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bbense/erlman/issues/2#issuecomment-113176066.

## 

Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by OnorioCatenacci** [comment]
Looks like you've got it Booker.  When I try to find ":os" now I get:

Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Erlh.h ":os"
:os not found

:ok 

But I do have the Erlang man pages on my machine so I'm not sure why it's not finding them. I'm going to close this issue; feel free to reopen it if you want.

**Comment by bbense** [comment]
What is the directory path to the erlang man pages on your machine?

thanks,
- Booker C. Bense

**Comment by OnorioCatenacci** [comment]
C:\program files\erl6.4\man

On Thu, Jun 18, 2015 at 5:14 PM, bbense notifications@github.com wrote:

> What is the directory path to the erlang man pages on your machine?
> 
> thanks,
> - Booker C. Bense
> 
> On Thu, Jun 18, 2015 at 9:06 AM, Onorio Catenacci <
> notifications@github.com>
> wrote:
> 
> > Looks like you've got it Booker. When I try to find ":os" now I get:
> > 
> > Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for
> > help)
> > iex(1)> Erlh.h ":os"
> > :os not found
> > 
> > :ok
> > 
> > But I do have the Erlang man pages on my machine so I'm not sure why it's
> > not finding them. I'm going to close this issue; feel free to reopen it
> > if
> > you want.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bbense/erlman/issues/2#issuecomment-113203464.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bbense/erlman/issues/2#issuecomment-113291840.

## 

Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by bbense** [comment]
Crap, they should be found then. Does this file exist on your machine? 

C:\program files\erl6.4\man\man3\ets.3

**Comment by OnorioCatenacci** [comment]
Yes, it's there.

BTW, just in case you're aware of some reason this would matter: I'm using
a Powershell command prompt to test things.  I see the same result under a
Cmd command prompt as well.

On Fri, Jun 19, 2015 at 10:52 AM, bbense notifications@github.com wrote:

> Crap, they should be found then. Does this file exist on your machine?
> 
> C:\program files\erl6.4\man\man3\ets.3
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bbense/erlman/issues/2#issuecomment-113536878.

## 

Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by bbense** [comment]
I don't know of any reason why that would matter. I guess I'm just going to have to bite the bullet and learn enough Windows to actually test this code there. Thanks again for your help.

**Comment by OnorioCatenacci** [comment]
I forked your code; I can test this for you but I probably won't get it
till later on today (Friday) or over the weekend.

On Fri, Jun 19, 2015 at 11:03 AM, bbense notifications@github.com wrote:

> I don't know of any reason why that would matter. I guess I'm just going
> to have to bite the bullet and learn enough Windows to actually test this
> code there.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bbense/erlman/issues/2#issuecomment-113540814.

## 

Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by OnorioCatenacci** [comment]
I haven't gotten a chance to look at this yet Booker.  Busy weekend.  But I will try to get some time on it tonight.  I'm tempted to say the issue is the space in the directory name ("C:/Program Files/erl6.4/man") because I've seen issues with that before.  But I need to test that of course.

**Comment by bbense** [comment]
I've gotten as far as being able to run iex on Windows. I'm still working
on figuring out how to run git,
so I can copy the code onto the box.

On Mon, Jun 22, 2015 at 10:43 AM, Onorio Catenacci <notifications@github.com

**Comment by OnorioCatenacci** [comment]
You can run git a couple of ways:

1.) Github for Windows: https://windows.github.com/

2.) Git For Windows: https://msysgit.github.io/

I personally prefer #2 because I'm a CLI guy but either of them should work.

On Mon, Jun 22, 2015 at 1:49 PM, bbense notifications@github.com wrote:

> I've gotten as far as being able to run iex on Windows. I'm still working
> on figuring out how to run git,
> so I can copy the code onto the box.
> 
> On Mon, Jun 22, 2015 at 10:43 AM, Onorio Catenacci <
> notifications@github.com
> 
> > wrote:
> > 
> > I haven't gotten a chance to look at this yet Booker. Busy weekend. But I
> > will try to get some time on it tonight. I'm tempted to say the issue is
> > the space in the directory name ("C:/Program Files/erl6.4/man") because
> > I've seen issues with that before. But I need to test that of course.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bbense/erlman/issues/2#issuecomment-114194757.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bbense/erlman/issues/2#issuecomment-114196921.

## 

Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by OnorioCatenacci** [comment]
Hi Booker,

Sorry I've not been in touch over the last couple of days.  I think the
best thing that I could try would be to either convert the Windows paths to
8.3 or to wrap them with double quotes.  I was working on hacking together
some code to do this so I could try it on Erlman.  I hope I can finish it
up today and give it a try.

As I say, I've not found the exact error yet but I've seen it happen
several times that spaces in directory names cause issues with Windows so I
think it's worth trying a fix on that front to see if it helps at all.

## 

Onorio

On Mon, Jun 22, 2015 at 2:46 PM, Onorio Catenacci Catenacci@ieee.org
wrote:

> You can run git a couple of ways:
> 
> 1.) Github for Windows: https://windows.github.com/
> 
> 2.) Git For Windows: https://msysgit.github.io/
> 
> I personally prefer #2 because I'm a CLI guy but either of them should
> work.
> 
> On Mon, Jun 22, 2015 at 1:49 PM, bbense notifications@github.com wrote:
> 
> > I've gotten as far as being able to run iex on Windows. I'm still working
> > on figuring out how to run git,
> > so I can copy the code onto the box.
> > 
> > On Mon, Jun 22, 2015 at 10:43 AM, Onorio Catenacci <
> > notifications@github.com
> > 
> > > wrote:
> > > 
> > > I haven't gotten a chance to look at this yet Booker. Busy weekend. But
> > > I
> > > will try to get some time on it tonight. I'm tempted to say the issue is
> > > the space in the directory name ("C:/Program Files/erl6.4/man") because
> > > I've seen issues with that before. But I need to test that of course.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/bbense/erlman/issues/2#issuecomment-114194757.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bbense/erlman/issues/2#issuecomment-114196921.
> 
> ## 
> 
> Onorio Catenacci
> 
> http://onor.io
> http://www.google.com/+OnorioCatenacci

## 

Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci
